server:
  port: 8080
  forward-headers-strategy: framework
  http2:
    enabled: ${SERVER_HTTP2_ENABLED:true}
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/css,application/javascript,application/openapi+json
    min-response-size: 2048

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: gateway-backend-trace
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive
    lazy-initialization: false
  messages:
    encoding: UTF-8
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${REDIS_HOST:redis}}
      port: ${SPRING_DATA_REDIS_PORT:${REDIS_PORT:6379}}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:${REDIS_TIMEOUT:2000ms}}

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 15s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  pre-loading-enabled: true
  swagger-ui:
    use-root-path-mapping: true
    urls:
      - url: /v3/api-docs/identity-backend
        name: identity-backend
      - url: /v3/api-docs/catalog-backend
        name: catalog-backend
      - url: /v3/api-docs/notifications-backend
        name: notifications-backend
      - url: /v3/api-docs/payment-backend
        name: payment-backend
      - url: /v3/api-docs/support-backend
        name: support-backend
      - url: /v3/api-docs/user-backend
        name: user-backend
      - url: /v3/api-docs/fitness-plan-backend
        name: fitness-plan-backend
      - url: /v3/api-docs/order-backend
        name: order-backend

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud: TRACE
    org.springframework.security: DEBUG
    org.springframework.boot: DEBUG
    az.fitnest.gateway: DEBUG